In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\krish naik data science bootcamp\python\venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\krish naik data science bootcamp\python\venv\lib\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\krish naik data science bootcamp\python\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\krish naik data science bootcamp\python\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\krish naik data science bootcamp\python\venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\krish naik data science bootcamp\python\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [154]:
# array,list, dict, tuple, set, matrix, vector

# Series in pandas 
- It is a one dimensional labelled array

In [155]:
import pandas as pd

In [156]:
s1 = pd.Series([10,20,30,40,50,60])
print(s1)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [157]:
s2 = pd.Series([10,20,30,40,50,60], index = ['a', 'b', 'c', 'd', 'e', 'f'], name = "scores")  # Changing index to alphabets
print(s2)

a    10
b    20
c    30
d    40
e    50
f    60
Name: scores, dtype: int64

In [158]:
# Create series from dict 

data = {'a': 10, 'b': 20, 'c': 30, 'd': 40}
s3 = pd.Series(data)
print(s3)

a    10
b    20
c    30
d    40
dtype: int64

In [159]:
import numpy as np

In [160]:
np_array = np.array([10, 20, 30, 40, 50, 60])
s4 = pd.Series(np_array)
print(s4)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [161]:
# Create series from dict 

data = {'a': 10, 'b' : "20", 'c': 1.11, 'd': True}
s6 = pd.Series(data)
print(s6)

a      10
b      20
c    1.11
d    True
dtype: object

In [162]:

data = {'a': 10, 'b' : "20", '1': 1.11, '2': True}
s5 = pd.Series(data)
print(s5)

a      10
b      20
1    1.11
2    True
dtype: object

In [163]:
# Create series from dict 

data = {'a': 10, 'b' : "20", 'c': 30, 'd': 40}
s7 = pd.Series(data , name = 'scores')
print(s7)

a    10
b    20
c    30
d    40
Name: scores, dtype: object

In [164]:
# 2D, 3D --> [[1,2], [23,3], [45,56]] --> flatten --> np.flatten() --> []

In [165]:
print(s7.index)
print(s7.values)

# dict ---> keys and values

print(s7.dtypes)
print(s7.name)
print(s7.shape)

Index(['a', 'b', 'c', 'd'], dtype='object')
[10 '20' 30 40]
object
scores
(4,)

# Series indexing and slicing

In [166]:
print(s7)

a    10
b    20
c    30
d    40
Name: scores, dtype: object

In [167]:
print(s7.values[0])

10

In [168]:
# Positional Indexing ---> It starts from Zero 
# Index --> 'a': 10, 'b':20, 'c': 30
# native index of value 10 is 0 i.e your positional indexing  access by s1.iloc["index"]
# s1.loc['a'] --> 10
# s1.iloc[0] --> 10
# s1[0] ---> deprecated (Not used in latets version, also devvelopers are not providing support) i.e loc native index

In [169]:
print(s7.loc['a']) # Indexing

10

In [170]:
print(s7.iloc[0]) # Positional Indexing

10

In [171]:
print(s7[0])

10

C:\Users\pnaik8\AppData\Local\Temp\ipykernel_21148\2729629825.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s7[0])

In [172]:
print(s7.loc[['a','b']]) # Indexing

a    10
b    20
Name: scores, dtype: object

In [173]:
print(s7.iloc[0:2])  # Positional indexing (exclusive)

a    10
b    20
Name: scores, dtype: object

In [174]:
data = {'a': 10, 'b' : 20, 'c': 30, 'd': 40, 0 : 100, 1: 101, 2: 400, 6:700}
s9 = pd.Series(data , name = 'scores')
print(s9)

a     10
b     20
c     30
d     40
0    100
1    101
2    400
6    700
Name: scores, dtype: int64

In [175]:
s9.loc[0:2]    # Inclusive - The index has to be present

0    100
1    101
2    400
Name: scores, dtype: int64

In [176]:
# Slicing 
# - loc[start, end ] : end is inclusive 
# - iloc [start, end ] : end is exclusive

# dataframe

In [177]:
data = {
    'Name' : ['Ananth', 'Pushpak', 'Nikhil'],
    'Age'  : [24, 26, 28],
    'City' : ['Bengaluru', 'Hyderabad', 'Delhi'
              ]}

In [178]:
df = pd.DataFrame(data)
print(df)

      Name  Age       City
0   Ananth   24  Bengaluru
1  Pushpak   26  Hyderabad
2   Nikhil   28      Delhi

In [179]:
data_1 = [
    {'Name' : 'Anath', 'Age': '24', 'City': 'Bengaluru'},
    {'Name' : 'Pushpak', 'Age': '26', 'City': 'Hyderabad'},
    {'Name' : 'Nikhil', 'Age': '28', 'City': 'Delhi'}


]

In [180]:
df_1 = pd.DataFrame(data_1)
print(df_1)

      Name Age       City
0    Anath  24  Bengaluru
1  Pushpak  26  Hyderabad
2   Nikhil  28      Delhi

In [181]:
arr_data = np.array([[1,2],[3,4],[5,6]])

In [182]:
df_2 = pd.DataFrame(arr_data)
print(df_2)

   0  1
0  1  2
1  3  4
2  5  6

In [183]:
df_2 = pd.DataFrame(arr_data, columns = ['A', 'B'])
print(df_2)

   A  B
0  1  2
1  3  4
2  5  6

# Accessing the Values

In [184]:
data = {
    'Name' : ['Ananth', 'Pushpak', 'Nikhil'],
    'Age'  : [24, 26, 28],
    'City' : ['Bengaluru', 'Hyderabad', 'Delhi'
              ]}

df_4 = pd.DataFrame(data)

In [185]:
print(df_4)

      Name  Age       City
0   Ananth   24  Bengaluru
1  Pushpak   26  Hyderabad
2   Nikhil   28      Delhi

In [186]:
type(df_4['Name'])

pandas.core.series.Series

In [187]:
print(df_4['Name'])
print("="*40)
print(df_4[['Name', 'Age']])
print("="* 40)
print(df.loc[0])
print("="*40)
print(df.loc[0:1]) # inclusive i.e Inclusive of index 1 
print("="*40)
print(df.iloc[0])
print("="*40)
print(df.iloc[0:1]) # Exclusive i.e Exclusive of index 1

0     Ananth
1    Pushpak
2     Nikhil
Name: Name, dtype: object
========================================
      Name  Age
0   Ananth   24
1  Pushpak   26
2   Nikhil   28
========================================
Name       Ananth
Age            24
City    Bengaluru
Name: 0, dtype: object
========================================
      Name  Age       City
0   Ananth   24  Bengaluru
1  Pushpak   26  Hyderabad
========================================
Name       Ananth
Age            24
City    Bengaluru
Name: 0, dtype: object
========================================
     Name  Age       City
0  Ananth   24  Bengaluru

# Data
#### .csv ---> Comma Seperated Values 
##### Name, Age
##### Monal, 30
##### Kevin, 26


#### .dict--> {'Name': ["Monal", "Kevin],              
####               'Age':[30,26],
####                }


#### Jason - Java Script opject notation
#### .jason --> [ 
    {'name' : 'Monal',
    'age' :30
    },
    {'name': 'Kevin',
    'age': 26}
    } 
]

# Working with real Dataset

In [188]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

In [189]:
df = pd.read_csv(titanic_dataset_github_url) # Raw Data

In [190]:
# Preview of the data Frame 

df.head()      # First 5 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [191]:
df.tail()   # last 5 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [192]:
print(df.tail())     # This is for terminal preview

     PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
886    male  27.0      0      0      211536  13.00   NaN        S
887  female  19.0      0      0      112053  30.00   B42        S
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S
889    male  26.0      0      0      111369  30.00  C148        C
890    male  32.0      0      0      370376   7.75   NaN        Q

In [193]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [194]:
df['Survived']

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [195]:
df[['Name', 'Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [196]:
df.loc[0] # First row

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [197]:
df.loc[0, 'Name']   # Name of the passenger at index 0

'Braund, Mr. Owen Harris'

In [198]:
df.loc[0:4]   # In loc the last value is inclusive

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [199]:
df.iloc[0]  # 1st row

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [200]:
df.iloc[0:4]  # 4th value is exclusive

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [201]:
df.iloc[:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [202]:
df.iloc[0,3]    # iloc only has positional index

'Braund, Mr. Owen Harris'

# Conditional Selection

In [203]:
# Get all the rows where person age is greater than 70 

# df[condition]

df[df['Age'] > 70]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [204]:
df[df['Age'] < 20]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
855,856,1,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.0,0,1,392091,9.3500,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [205]:
# Save data using a varibale so we can use it later
older_passengers = df[df['Age'] > 70]
older_passengers.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [206]:
# Get all the females who survived 

df[(df['Sex'] == 'female') & df['Survived'] == 1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [207]:
# Only name and age of all the females who survived 

female_surviors_subset = df[(df['Sex'] == 'female') & df['Survived'] == 1][['Name', 'Age']]
female_surviors_subset.head(10)

                                                 Name   Age
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                              Heikkinen, Miss. Laina  26.0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                 Nasser, Mrs. Nicholas (Adele Achem)  14.0
10                    Sandstrom, Miss. Marguerite Rut   4.0
11                           Bonnell, Miss. Elizabeth  58.0
15                   Hewlett, Mrs. (Mary D Kingcome)   55.0
19                            Masselmani, Mrs. Fatima   NaN
22                        McGowan, Miss. Anna "Annie"  15.0

In [208]:
# Total Number of survivals 

survived = len(df[df['Survived'] == 1])
notsurvived = len(df[df['Survived']== 0])
print(notsurvived + survived)

891

In [209]:
survived/(notsurvived + survived)

0.3838383838383838

In [210]:
notsurvived/(notsurvived + survived)

0.6161616161616161

In [211]:
# Females who survived with name and age 

female_surviors_subset_loc = df.loc[(df['Sex'] == 'female') & df['Survived'] == 1][['Name', 'Age']]
female_surviors_subset_loc.head()

                                                Name   Age
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0

In [212]:
df.loc[0, ['Cabin']]    # df.loc uses square brackets , Square bracekt [] is used in list, array and dataFrame

Cabin    NaN
Name: 0, dtype: object

# Slicing Rows and Columns

In [213]:
df.loc[0:4, ['Name', 'Age']]

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [214]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [215]:
# I want first 3 rows and first 2 columns only using numbers and index 

df.iloc[0:3, 0:2]

   PassengerId  Survived
0            1         0
1            2         1
2            3         1

In [216]:
# First 3 rows and selected columns by index, I want only columns 1 and 3

df.iloc[0:3,[1,3] ]

   Survived                                               Name
0         0                            Braund, Mr. Owen Harris
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1                             Heikkinen, Miss. Laina

In [217]:
# I want name as first column and surved as second column 

df.iloc[0:3, [3,1]]

                                                Name  Survived
0                            Braund, Mr. Owen Harris         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                             Heikkinen, Miss. Laina         1

In [218]:
df.loc[0:3, ['Name', 'Survived']]

                                                Name  Survived
0                            Braund, Mr. Owen Harris         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                             Heikkinen, Miss. Laina         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)         1

In [219]:
df.loc[0:3, ['Survived', 'Name']]

   Survived                                               Name
0         0                            Braund, Mr. Owen Harris
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1                             Heikkinen, Miss. Laina
3         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)

In [220]:
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [221]:
# Adding age + 1 by creating a subset 


subset = df[df['Sex'] == 'male']
subset['Age'] = subset['Age'] + 1

print(subset)

     PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male
4              5         0       3        Allen, Mr. William Henry  male
5              6         0       3                Moran, Mr. James  male
6              7         0       1         McCarthy, Mr. Timothy J  male
7              8         0       3  Palsson, Master. Gosta Leonard  male
..           ...       ...     ...                             ...   ...
883          884         0       2   Banfield, Mr. Frederick James  male
884          885         0       3          Sutehall, Mr. Henry Jr  male
886          887         0       2           Montvila, Rev. Juozas  male
889          890         1       1           Behr, Mr. Karl Howell  male
890          891         0       3             Dooley, Mr. Patrick  male

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0    23.0      1      0         A/5 21171   7.2500   NaN        S
4    36.0      0      0            373450   8.0500   NaN        S
5     NaN      0      0            330877   8.4583   NaN        Q
6    55.0      0      0             17463  51.8625   E46        S
7     3.0      3      1            349909  21.0750   NaN        S
..    ...    ...    ...               ...      ...   ...      ...
883  29.0      0      0  C.A./SOTON 34068  10.5000   NaN        S
884  26.0      0      0   SOTON/OQ 392076   7.0500   NaN        S
886  28.0      0      0            211536  13.0000   NaN        S
889  27.0      0      0            111369  30.0000  C148        C
890  33.0      0      0            370376   7.7500   NaN        Q

[577 rows x 12 columns]

C:\Users\pnaik8\AppData\Local\Temp\ipykernel_21148\1614144536.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset['Age'] = subset['Age'] + 1

In [222]:
subset = df[df['Sex'] == 'male'].copy()  # Copy and then change the value . Here copy will create a new reference, Copy will not change your original data 
subset['Age'] += 1
print(subset)

     PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male
4              5         0       3        Allen, Mr. William Henry  male
5              6         0       3                Moran, Mr. James  male
6              7         0       1         McCarthy, Mr. Timothy J  male
7              8         0       3  Palsson, Master. Gosta Leonard  male
..           ...       ...     ...                             ...   ...
883          884         0       2   Banfield, Mr. Frederick James  male
884          885         0       3          Sutehall, Mr. Henry Jr  male
886          887         0       2           Montvila, Rev. Juozas  male
889          890         1       1           Behr, Mr. Karl Howell  male
890          891         0       3             Dooley, Mr. Patrick  male

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0    23.0      1      0         A/5 21171   7.2500   NaN        S
4    36.0      0      0            373450   8.0500   NaN        S
5     NaN      0      0            330877   8.4583   NaN        Q
6    55.0      0      0             17463  51.8625   E46        S
7     3.0      3      1            349909  21.0750   NaN        S
..    ...    ...    ...               ...      ...   ...      ...
883  29.0      0      0  C.A./SOTON 34068  10.5000   NaN        S
884  26.0      0      0   SOTON/OQ 392076   7.0500   NaN        S
886  28.0      0      0            211536  13.0000   NaN        S
889  27.0      0      0            111369  30.0000  C148        C
890  33.0      0      0            370376   7.7500   NaN        Q

[577 rows x 12 columns]

In [223]:
print(subset.head(2))
print(df.head(2))

   PassengerId  Survived  Pclass                      Name   Sex   Age  SibSp  \
0            1         0       3   Braund, Mr. Owen Harris  male  23.0      1
4            5         0       3  Allen, Mr. William Henry  male  36.0      0

   Parch     Ticket  Fare Cabin Embarked
0      0  A/5 21171  7.25   NaN        S
4      0     373450  8.05   NaN        S
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1

   Parch     Ticket     Fare Cabin Embarked
0      0  A/5 21171   7.2500   NaN        S
1      0   PC 17599  71.2833   C85        C

In [224]:
# iloc ---> copy
# loc ---> may be view 
# df[...] --> may be view

In [225]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [226]:
df_by_name = df.set_index('Name')
df_by_name.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [227]:
print(df_by_name.loc["Allen, Mr. William Henry"])

PassengerId         5
Survived            0
Pclass              3
Sex              male
Age              35.0
SibSp               0
Parch               0
Ticket         373450
Fare             8.05
Cabin             NaN
Embarked            S
Name: Allen, Mr. William Henry, dtype: object

In [228]:
df_by_name.reset_index()
df_by_name.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [229]:
df_by_name.reset_index(inplace = True)
df_by_name.head()

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Reindex

In [232]:
sales_jan = pd.DataFrame({
    'Sales': [250, 400, 300]
}, index = ['Store_A', 'Store_B', 'Store_C'])

sales_jan

         Sales
Store_A    250
Store_B    400
Store_C    300

In [235]:
sales_feb = pd.DataFrame({
    'Sales': [260,310]
}, index = ['Store_A','Store_C'])

sales_feb

         Sales
Store_A    260
Store_C    310

In [237]:
common_index = sales_jan.index

In [239]:
sales_feb_aligned = sales_feb.reindex(common_index)

In [240]:
sales_feb_aligned

         Sales
Store_A  260.0
Store_B    NaN
Store_C  310.0

In [245]:
sales_diff = sales_feb_aligned['Sales'] - sales_jan['Sales']

sales_diff

Store_A    10.0
Store_B     NaN
Store_C    10.0
Name: Sales, dtype: float64

In [249]:
sales_feb_aligned = sales_feb.reindex(common_index, fill_value = 0)

sales_feb_aligned

         Sales
Store_A    260
Store_B      0
Store_C    310

In [250]:
sales_diff = sales_feb_aligned['Sales'] - sales_jan['Sales']

sales_diff

Store_A     10
Store_B   -400
Store_C     10
Name: Sales, dtype: int64

In [256]:
sales_feb_new = pd.DataFrame({
    'Sales': [260,310, 100]
}, index = ['Store_A','Store_C', 'Store_D'])

sales_feb_new

         Sales
Store_A    260
Store_C    310
Store_D    100

In [257]:
common_index = list(set(list(sales_jan.index)+ list(sales_feb.index)))

In [258]:
common_index

['Store_B', 'Store_D', 'Store_A', 'Store_C']

In [263]:
sales_jan_aligned = sales_jan.reindex(common_index, fill_value = 0)
sales_jan_aligned

         Sales
Store_B    400
Store_D      0
Store_A    250
Store_C    300

In [264]:
sales_feb_new_aligned = sales_feb_new.reindex(common_index, fill_value = 0)
sales_feb_new_aligned

         Sales
Store_B      0
Store_D    100
Store_A    260
Store_C    310

In [266]:
to_check = 'Store_C'
print(sales_feb_aligned.loc[to_check])
print(sales_jan_aligned.loc[to_check])

Sales    310
Name: Store_C, dtype: int64
Sales    300
Name: Store_C, dtype: int64

# For Columns

In [269]:
source_a = pd.DataFrame({
     'Product': ['Laptop', 'Tablet', 'Phone'],
     'Price': [1000, 500, 800],
     'Stock': [30, 50, 100]
})

source_a

  Product  Price  Stock
0  Laptop   1000     30
1  Tablet    500     50
2   Phone    800    100

In [271]:
source_b = pd.DataFrame({
    'Price': [980, 520, 810],
    'Product': ['Laptop', 'Tablet', 'Phone']
})

source_b

   Price Product
0    980  Laptop
1    520  Tablet
2    810   Phone

In [273]:
aligned_b = source_b.reindex(columns = source_a.columns, fill_value = 0)

aligned_b

  Product  Price  Stock
0  Laptop    980      0
1  Tablet    520      0
2   Phone    810      0

# Iteration in Pandas

In [275]:
df = pd.DataFrame({
    'Name' : ['heartline', 'gagan', 'gavin'],
    'Age' : [25,30,23],
    'City' : ['Delhi', 'Mumbai', 'Chennai']
})

In [281]:
for index, row in df.iterrows():
    print(f"{index}: {row['Name']} lives in {row['City']} and is {row['Age']} years old.")

0: heartline lives in Delhi and is 25 years old.
1: gagan lives in Mumbai and is 30 years old.
2: gavin lives in Chennai and is 23 years old.

In [290]:
for row in df.itertuples():
    print(f"{row.Name} lives in {row.City}, and is {row.Age} years old.", end='\\n\\n')

heartline lives in Delhi, and is 25 years old.\n\ngagan lives in Mumbai, and is 30 years old.\n\ngavin lives in Chennai, and is 23 years old.\n\n

In [291]:
df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [292]:
for i in df.index:
    print(i)

0
1
2

In [295]:
for col in df.columns:
    print(f"Column:{col}")
    print(df[col].values, end = '\n\n')

Column:Name
['heartline' 'gagan' 'gavin']

Column:Age
[25 30 23]

Column:City
['Delhi' 'Mumbai' 'Chennai']

# Condition based column creation using custom logic

In [296]:
df.head()

        Name  Age     City
0  heartline   25    Delhi
1      gagan   30   Mumbai
2      gavin   23  Chennai

In [297]:
# if >= 30, senior else young

In [300]:
values = []
for idx, row in df.iterrows():
    if row['Age'] < 30:
        values.append('young')
    else:
        values.append('Senior')

df['Category'] = values

In [301]:
df

        Name  Age     City Category
0  heartline   25    Delhi    young
1      gagan   30   Mumbai   Senior
2      gavin   23  Chennai    young

In [302]:
# vectorized using apply

In [304]:
df = pd.DataFrame({
    'Name' : ['heartline', 'gagan', 'gavin'],
    'Age' : [25,30,23],
    'City' : ['Delhi', 'Mumbai', 'Chennai']
})

In [305]:
df['Categories'] = df['Age'].apply(lambda age: 'young' if age < 30 else 'senior')

In [306]:
df

        Name  Age     City Categories
0  heartline   25    Delhi      young
1      gagan   30   Mumbai     senior
2      gavin   23  Chennai      young

In [ ]:
# iterrows < itertuples < apply

# SORT 

1. sort_values --- > data Values
2. sort_index --> rows/columns

In [309]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df = pd.read_csv(titanic_dataset_github_url)

In [310]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [313]:
# Sorted by Age 

sorted_df = df.sort_values(by = 'Age')
sorted_df[['Name', 'Age']].head(5)

                                Name   Age
803  Thomas, Master. Assad Alexander  0.42
755        Hamalainen, Master. Viljo  0.67
644           Baclini, Miss. Eugenie  0.75
469    Baclini, Miss. Helene Barbara  0.75
78     Caldwell, Master. Alden Gates  0.83

In [314]:
sorted_df[['Name', 'Age']].tail(5)

                                         Name  Age
859                          Razi, Mr. Raihed  NaN
863         Sage, Miss. Dorothy Edith "Dolly"  NaN
868               van Melkebeke, Mr. Philemon  NaN
878                        Laleff, Mr. Kristo  NaN
888  Johnston, Miss. Catherine Helen "Carrie"  NaN

In [316]:
sorted_df.loc[0:100, ['Name', 'Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
289                               Connolly, Miss. Kate  22.0
323  Caldwell, Mrs. Albert Francis (Sylvia Mae Harb...  22.0
243                      Maenpaa, Mr. Matti Alexanteri  22.0
521                                    Vovk, Mr. Janko  22.0
..                                                 ...   ...
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0
399                   Trout, Mrs. William H (Jessie L)  28.0
392                       Gustafsson, Mr. Johan Birger  28.0
635                                  Davis, Miss. Mary  28.0
100                            Petranec, Miss. Matilda  28.0

[146 rows x 2 columns]

In [320]:
print(df['Age'].dtype)

float64

In [321]:
sorted_df = df.sort_values(by = 'Age')
print(sorted_df[['Name', "Age"]].tail(20))

                                             Name  Age
776                              Tobin, Mr. Roger  NaN
778                       Kilgannon, Mr. Thomas J  NaN
783                        Johnston, Mr. Andrew G  NaN
790                      Keane, Mr. Andrew "Andy"  NaN
792                       Sage, Miss. Stella Anna  NaN
793                      Hoyt, Mr. William Fisher  NaN
815                              Fry, Mr. Richard  NaN
825                               Flynn, Mr. John  NaN
826                                  Lam, Mr. Len  NaN
828                  McCormack, Mr. Thomas Joseph  NaN
832                                Saad, Mr. Amin  NaN
837                           Sirota, Mr. Maurice  NaN
839                          Marechal, Mr. Pierre  NaN
846                      Sage, Mr. Douglas Bullen  NaN
849  Goldenberg, Mrs. Samuel L (Edwiga Grabowska)  NaN
859                              Razi, Mr. Raihed  NaN
863             Sage, Miss. Dorothy Edith "Dolly"  NaN
868                   van Melkebeke, Mr. Philemon  NaN
878                            Laleff, Mr. Kristo  NaN
888      Johnston, Miss. Catherine Helen "Carrie"  NaN

In [324]:
# Sort by multiple columns 

df_sorted = df.sort_values(by = ['Pclass', 'Fare'])   # Ascending order

In [325]:
df_sorted.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
263,264,0,1,"Harrison, Mr. William",male,40.0,0,0,112059,0.0,B94,S
633,634,0,1,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0,NaN,S
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0,A36,S
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0,B102,S
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0,NaN,S

In [330]:
df_sorted = df.sort_values(by = ['Pclass', 'Fare'], ascending = [True,False]) # ascending order

In [331]:
df_sorted.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S

In [333]:
# Sort Index 

df_sorted.to_csv("a.csv")

In [334]:
# Sort index

In [335]:
# axis = 0 # rows
# axis = 1 # Columns

In [336]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [339]:
df_sort_2 = df.set_index('PassengerId')

In [342]:
df_sorted_by_index = df_sort_2.sort_index(axis = 0)

In [343]:
df_sorted_by_index.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [347]:
df_sorted_by_index_c = df_sort_2.sort_index(axis = 0, ascending = False)
df_sorted_by_index.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [348]:
# df_sorted_by_index_c = df_sort_2.sort_index(axis = 0, ascending = False, inplace = True )

# Sorting Columns alphapetically

In [349]:
df_sorted_cols = df.sort_index(axis = 1)

In [350]:
df_sorted_cols.head()

,Age,Cabin,Embarked,Fare,Name,Parch,PassengerId,Pclass,Sex,SibSp,Survived,Ticket
0,22.0,NaN,S,7.2500,"Braund, Mr. Owen Harris",0,1,3,male,1,0,A/5 21171
1,38.0,C85,C,71.2833,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,2,1,female,1,1,PC 17599
2,26.0,NaN,S,7.9250,"Heikkinen, Miss. Laina",0,3,3,female,0,1,STON/O2. 3101282
3,35.0,C123,S,53.1000,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,4,1,female,1,1,113803
4,35.0,NaN,S,8.0500,"Allen, Mr. William Henry",0,5,3,male,0,0,373450

# Changing column order in Pandas

In [351]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df = pd.read_csv(titanic_dataset_github_url)

In [352]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [353]:
new_order = ['Name', 'Sex', 'Age', 'Pclass', 'Fare', 'Survived']

In [354]:
df_reordered = df[new_order]
print(df_reordered.head())

                                                Name     Sex   Age  Pclass  \
0                            Braund, Mr. Owen Harris    male  22.0       3
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0       1
2                             Heikkinen, Miss. Laina  female  26.0       3
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0       1
4                           Allen, Mr. William Henry    male  35.0       3

      Fare  Survived
0   7.2500         0
1  71.2833         1
2   7.9250         1
3  53.1000         1
4   8.0500         0

In [355]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [356]:
sorted(df.columns)

['Age',
 'Cabin',
 'Embarked',
 'Fare',
 'Name',
 'Parch',
 'PassengerId',
 'Pclass',
 'Sex',
 'SibSp',
 'Survived',
 'Ticket']

In [359]:
df.df_reordered = df[sorted(df.columns)]

df_reordered.head()

C:\Users\pnaik8\AppData\Local\Temp\ipykernel_21148\4020761821.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.df_reordered = df[sorted(df.columns)]

,Name,Sex,Age,Pclass,Fare,Survived
0,"Braund, Mr. Owen Harris",male,22.0,3,7.2500,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,71.2833,1
2,"Heikkinen, Miss. Laina",female,26.0,3,7.9250,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,53.1000,1
4,"Allen, Mr. William Henry",male,35.0,3,8.0500,0

# Working with text data

In [360]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [363]:
print(df[['Name', 'Sex', 'Cabin']].head(10))

                                                Name     Sex Cabin
0                            Braund, Mr. Owen Harris    male   NaN
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   C85
2                             Heikkinen, Miss. Laina  female   NaN
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  C123
4                           Allen, Mr. William Henry    male   NaN
5                                   Moran, Mr. James    male   NaN
6                            McCarthy, Mr. Timothy J    male   E46
7                     Palsson, Master. Gosta Leonard    male   NaN
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female   NaN
9                Nasser, Mrs. Nicholas (Adele Achem)  female   NaN

In [362]:
df['Name'].str.capitalize()

0                                Braund, mr. owen harris
1      Cumings, mrs. john bradley (florence briggs th...
2                                 Heikkinen, miss. laina
3           Futrelle, mrs. jacques heath (lily may peel)
4                               Allen, mr. william henry
                             ...
886                                Montvila, rev. juozas
887                         Graham, miss. margaret edith
888             Johnston, miss. catherine helen "carrie"
889                                Behr, mr. karl howell
890                                  Dooley, mr. patrick
Name: Name, Length: 891, dtype: object

In [365]:
df['Name'].str.len()   # Length of all the names

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [367]:
# Replace MR with Sir 

df['Name'].str.replace("Mr.", "Sir", regex = False)

0                                Braund, Sir Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Sir William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Sir Karl Howell
890                                  Dooley, Sir Patrick
Name: Name, Length: 891, dtype: object

In [368]:
df['Name'].str.replace(r"\(.*\)", "", regex=True) # Removes anything inside the parentheses + parentheses

0                       Braund, Mr. Owen Harris
1                   Cumings, Mrs. John Bradley
2                        Heikkinen, Miss. Laina
3                 Futrelle, Mrs. Jacques Heath
4                      Allen, Mr. William Henry
                         ...
886                       Montvila, Rev. Juozas
887                Graham, Miss. Margaret Edith
888    Johnston, Miss. Catherine Helen "Carrie"
889                       Behr, Mr. Karl Howell
890                         Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [369]:
df['Name'].str.split(",", expand=True)[0] #returns a DataFrame with each split part as a column

0         Braund
1        Cumings
2      Heikkinen
3       Futrelle
4          Allen
         ...
886     Montvila
887       Graham
888     Johnston
889         Behr
890       Dooley
Name: 0, Length: 891, dtype: object

In [371]:
df['Name'].str.find("Mr")

0       8
1       9
2      -1
3      10
4       7
       ..
886    -1
887    -1
888    -1
889     6
890     8
Name: Name, Length: 891, dtype: int64

In [373]:
count = df['Name'].str.contains("Miss").sum()

In [374]:
print(count)

182

In [57]:
import pandas as pd
import numpy as np

In [2]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"
   
iris_dataset_github_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv"
    
kaggle_link = "https://www.kaggle.com/datasets/yasserh/titanic-dataset/data"

In [3]:
df = pd.read_csv(titanic_dataset_github_url)

# Find Position of Substring

In [4]:
df['Name'].str.find("Mr")

0       8
1       9
2      -1
3      10
4       7
       ..
886    -1
887    -1
888    -1
889     6
890     8
Name: Name, Length: 891, dtype: int64

In [5]:
# Count Passengers with "Miss" in name

count = df['Name'].str.contains("Miss").sum()
print("Number of 'Miss' : ", count)

Number of 'Miss' :  182

In [11]:
data = {
    "Name" : [
        'Monal K', 'Bhuvika', 'Niranjan', 'riyan'
    ],
    'Email': ['m@gmail.com', 'b@gmail.com', 'c@gmail.com', 'd@gmail.com'
              ]
}
df = pd.DataFrame(data)

In [12]:
df.head()

       Name        Email
0   Monal K  m@gmail.com
1   Bhuvika  b@gmail.com
2  Niranjan  c@gmail.com
3     riyan  d@gmail.com

In [13]:
# Replace K with something else

df['Name'].str.replace("K", "Kumar", regex = False)

0    Monal Kumar
1        Bhuvika
2       Niranjan
3          riyan
Name: Name, dtype: object

In [14]:
df['Name'].str.pad(width = 20, side = 'left', fillchar = '-')

0    -------------Monal K
1    -------------Bhuvika
2    ------------Niranjan
3    ---------------riyan
Name: Name, dtype: object

# Options and Customizations

In [15]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df = titanic_dataset_github_url

In [18]:
df = pd.read_csv(titanic_dataset_github_url)

In [21]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [22]:
# You cant see all columns and rows here 

pd.set_option('display.max_rows', 5)

In [23]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
...,...,...,...,...,...,...,...,...,...,...,...,...
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [25]:
# Show all columns (None())
pd.set_option('display.max_columns', None)

In [26]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
...,...,...,...,...,...,...,...,...,...,...,...,...
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [27]:
pd.set_option('display.max_columns', 3)
df

     PassengerId  ...  Embarked
0              1  ...         S
1              2  ...         C
..           ...  ...       ...
889          890  ...         C
890          891  ...         Q

[891 rows x 12 columns]

In [37]:
pd.set_option('display.max_columns', 30)

In [38]:
df[['Fare', 'Age']].head()

      Fare   Age
0   7.2500  22.0
1  71.2833  38.0
2   7.9250  26.0
3  53.1000  35.0
4   8.0500  35.0

In [ ]:
# Set Float Precision to 2 Decimal Places. How to display we are not changing anything

pd.set_option('display.float_format', '{:.2f}'.format)

In [41]:
df[['Fare', 'Age']].head()

   Fare   Age
0  7.25 22.00
1 71.28 38.00
2  7.92 26.00
3 53.10 35.00
4  8.05 35.00

In [43]:
# Check current value of an Option 

pd.get_option('display.max_rows')

5

In [49]:
# Temporaily set option (context Manager)
with pd.option_context('display.max_rows', 3):       # Max rows only for viewing it wont change anything
    print(df)

     PassengerId  Survived  Pclass                     Name   Sex   Age  \
0              1         0       3  Braund, Mr. Owen Harris  male 22.00
..           ...       ...     ...                      ...   ...   ...
890          891         0       3      Dooley, Mr. Patrick  male 32.00

     SibSp  Parch     Ticket  Fare Cabin Embarked
0        1      0  A/5 21171  7.25   NaN        S
..     ...    ...        ...   ...   ...      ...
890      0      0     370376  7.75   NaN        Q

[891 rows x 12 columns]

In [50]:
# Resetting to Default 

pd.reset_option('display.max_rows')

In [51]:
pd.get_option('display.max_rows')

60

In [53]:
# You can reset all options

pd.reset_option('all')

C:\Users\pnaik8\AppData\Local\Temp\ipykernel_7316\3192342.py:3: FutureWarning: data_manager option is deprecated and will be removed in a future version. Only the BlockManager will be available.
  pd.reset_option('all')
C:\Users\pnaik8\AppData\Local\Temp\ipykernel_7316\3192342.py:3: FutureWarning: use_inf_as_na option is deprecated and will be removed in a future version. Convert inf values to NaN before operating instead.
  pd.reset_option('all')

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [ ]:
import warnings

with warnings.catch_warnings():
    warnings.simplefilter('ignore', FutureWarning)
    pd.reset_option('all')

# Categorical data

In [68]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,male
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,female
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,female
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,female
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,male

In [ ]:
print(df['Sex'].dtype)    # Data type is a string for this object

object

In [ ]:
# Convert a coumn to categorical 
df['sex_c'] = df['Sex'].astype('category')       # Data type is a Categorical i.e Male and Female are two sepeate groups
df[['Sex', 'sex_c']].head()

      Sex   sex_c
0    male    male
1  female  female
2  female  female
3  female  female
4    male    male

In [77]:
print(df['Sex'].dtype)
print(df['Sex_c'].dtype)

object
category

In [ ]:
df['Sex_c_categorical_codes'] = df['Sex_c'].cat.codes     # Converting categories into individual codes  Here Sex_c is categorical column

In [79]:
df[['Sex','Sex_c', 'Sex_c_categorical_codes']].head()

      Sex   Sex_c  Sex_c_categorical_codes
0    male    male                        1
1  female  female                        0
2  female  female                        0
3  female  female                        0
4    male    male                        1

In [ ]:
# Machine learning cannot understand strings it only understands 0 and 1

In [ ]:
df['Sex_apply_category'] = df['Sex'].apply(lambda x : 0 if x == 'male' else 1 ) # Python method for doing it

In [81]:
df[['Sex','Sex_c', 'Sex_c_categorical_codes']].head()

      Sex   Sex_c  Sex_c_categorical_codes
0    male    male                        1
1  female  female                        0
2  female  female                        0
3  female  female                        0
4    male    male                        1

In [82]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_C,Sex_c,sex_c,Sex_c_categorical_codes,Sex_apply_category
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,male,male,male,1,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,female,female,female,0,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,female,female,female,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,female,female,female,0,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,male,male,male,1,0

In [84]:
df['Pclass'].unique()

array([3, 1, 2])

In [85]:
df['Pclass_new_weird'] = df['Pclass'].apply(lambda x: 'adf' if x == 3 else ('wer' if x == 2 else 'tyu'))

In [86]:
df[['Pclass', 'Pclass_new_weird']].head(10)

   Pclass Pclass_new_weird
0       3              adf
1       1              tyu
2       3              adf
3       1              tyu
4       3              adf
5       3              adf
6       1              tyu
7       3              adf
8       3              adf
9       2              wer

In [ ]:
# Analysis : 
# tyu > adf > wer

In [87]:
print(df['Pclass'].dtype)
print(df['Pclass_new_weird'].dtype)

int64
object

In [89]:
df['Pclass_new_weird_ordered'] = pd.Categorical(
    df['Pclass_new_weird'],
    categories = ['wer','adf','tyu'],  # Custom order (ascending)
    ordered = True 
)

In [91]:
print(df['Pclass_new_weird_ordered'].dtype)

category

In [92]:
df['Pclass_new_weird_ordered'].cat.categories

Index(['wer', 'adf', 'tyu'], dtype='object')

In [95]:
df['Pclass_new_weird_ordered'] > 'wer'

0       True
1       True
2       True
3       True
4       True
       ...
886    False
887     True
888     True
889     True
890     True
Name: Pclass_new_weird_ordered, Length: 891, dtype: bool

# Date Functionality

In [96]:
df = pd.DataFrame({
       'event': ['Concert', 'Conference', 'Wedding', 'Reception', 'last_day'],
       'date': ['2025-01-01', '2025-03-15', '2025-07-20', '2025-07-21', '2025-07-31']
})

In [99]:
df['date_pandas'] = pd.to_datetime(df['date'])

In [100]:
df.head()

        event        date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15
2     Wedding  2025-07-20  2025-07-20
3   Reception  2025-07-21  2025-07-21
4    last_day  2025-07-31  2025-07-31

In [102]:
print(df.dtypes[['event', 'date', 'date_pandas']])

event                  object
date                   object
date_pandas    datetime64[ns]
dtype: object

In [103]:
df['date_pandas'].dt.year

0    2025
1    2025
2    2025
3    2025
4    2025
Name: date_pandas, dtype: int32

In [104]:
df['date_pandas'].dt.month

0    1
1    3
2    7
3    7
4    7
Name: date_pandas, dtype: int32

In [105]:
df['date_pandas'].dt.day

0     1
1    15
2    20
3    21
4    31
Name: date_pandas, dtype: int32

In [106]:
df['date_pandas'].dt.weekday

0    2
1    5
2    6
3    0
4    3
Name: date_pandas, dtype: int32

In [107]:
df['date_pandas'].dt.day_name()

0    Wednesday
1     Saturday
2       Sunday
3       Monday
4     Thursday
Name: date_pandas, dtype: object

In [108]:
df['date_pandas'].dt.is_month_end

0    False
1    False
2    False
3    False
4     True
Name: date_pandas, dtype: bool

In [110]:
df[df['date_pandas'] > '2025-04-02']

       event        date date_pandas
2    Wedding  2025-07-20  2025-07-20
3  Reception  2025-07-21  2025-07-21
4   last_day  2025-07-31  2025-07-31

In [111]:
df[df['date_pandas'].between('2025-01-01', '2025-06-01')]

        event        date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15

In [112]:
# Date Range 

pd.date_range(start = '2024-01-01', end = '2024-01-10', freq = 'D')

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
pd.date_range(start = '2024-01-01', end = '2024-03-10', freq = 'ME')   # Month End

DatetimeIndex(['2024-01-31', '2024-02-29'], dtype='datetime64[ns]', freq='ME')

In [115]:
pd.date_range(start = '2024-01-01', end = '2024-03-10', freq = 'MS') # Month Start

DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01'], dtype='datetime64[ns]', freq='MS')

# Date Arithmetic

In [116]:
df['next_week'] = df['date_pandas'] + pd.Timedelta(days = 7)

In [117]:
df[['date_pandas', 'next_week']]

  date_pandas  next_week
0  2025-01-01 2025-01-08
1  2025-03-15 2025-03-22
2  2025-07-20 2025-07-27
3  2025-07-21 2025-07-28
4  2025-07-31 2025-08-07

In [118]:
df['days_to_event'] = df['date_pandas'] - pd.Timestamp.today()

In [119]:
df.head()

        event        date date_pandas  next_week              days_to_event
0     Concert  2025-01-01  2025-01-01 2025-01-08 -394 days +09:06:47.326069
1  Conference  2025-03-15  2025-03-15 2025-03-22 -321 days +09:06:47.326069
2     Wedding  2025-07-20  2025-07-20 2025-07-27 -194 days +09:06:47.326069
3   Reception  2025-07-21  2025-07-21 2025-07-28 -193 days +09:06:47.326069
4    last_day  2025-07-31  2025-07-31 2025-08-07 -183 days +09:06:47.326069

In [120]:
165/30

5.5

In [ ]:
# Assignmnet 

# TODO - While creating a task, ask user about the deadline 

# Start Date - Pick automatically from today's date 

# Deadline - 7,10,10

# 1. Task-1| Days left | Green-color
# 2. Task-2| Days left | Red -color        
# 3. Task-3| Days left | Green - color
# 4. Task-4| Days left | Red-color